# Generated by Django 2.1.3 on 2018-12-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_act',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
