# Generated by Django 2.1.3 on 2018-12-06 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_topic_topic_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='upd_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
